<?xml version="1.0"?>
<robot name="phoenix" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="phoenix_properties.xacro"/>

    <link name="base_link"/>

    <link name="swivel_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 ${-swivel_l/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${swivel_r}" length="${swivel_l}"/>
                </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${-swivel_l/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${swivel_r}" length="${swivel_l}"/>
                </geometry>
        </collision>
    </link>

    <link name="upper_arm_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 ${upper_arm_l/2 + 0.028}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${upper_arm_r}" length="${upper_arm_l}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
           <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${upper_arm_r}" length="${upper_arm_l}"/>
            </geometry>
        </collision>
    </link>

    <link name="gearbox_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${gearbox_r}" length="${gearbox_l}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${gearbox_r}" length="${gearbox_l}"/>
            </geometry>
        </collision>
    </link>

    <link name="lower_arm_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 ${lower_arm_l / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lower_arm_r}" length="${lower_arm_l}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${lower_arm_l / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lower_arm_r}" length="${lower_arm_l}"/>
            </geometry>
        </collision>
    </link>

    <link name="wrist_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 ${wrist_l / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wrist_r}" length="${wrist_l}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${wrist_l / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wrist_r}" length="${wrist_l}"/>
            </geometry>
        </collision>
    </link>

    <link name="wrist_rotation_link"/>

    <link name="left_finger">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 ${-finger_l/2} ${finger_h / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${finger_w} ${finger_l} ${finger_h}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 ${-finger_l/2} ${finger_h / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${finger_w} ${finger_l} ${finger_h}"/>
            </geometry>
        </collision>
    </link>

     <link name="right_finger">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0.0 ${finger_l/2} ${finger_h / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${finger_w} ${finger_l} ${finger_h}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 ${finger_l/2} ${finger_h / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${finger_w} ${finger_l} ${finger_h}"/>
            </geometry>
        </collision>
    </link>




    <joint name="base_swivel_joint" type="revolute">
        <origin xyz="0.0 0.0 ${swivel_l}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="swivel_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${-pi}" upper="${pi}" effort="100.0" velocity="100.0"/>
    </joint>

    <joint name="swivel_upper_arm_joint" type="revolute">
        <origin xyz="0.0 0.0 ${0.0381}" rpy="0.0 0.0 0.0"/>
        <parent link="swivel_link"/>
        <child link="upper_arm_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100.0" velocity="100.0"/>
    </joint>

    <joint name="upper_arm_gearbox_joint" type="fixed">
        <origin xyz="0.0 ${-gearbox_l} ${0.028 + upper_arm_l + gearbox_r}" rpy="0.0 0.0 0.0"/>
        <parent link="upper_arm_link"/>
        <child link="gearbox_link"/>
    </joint>

    <joint name="gearbox_lower_arm_joint" type="revolute">
        <origin xyz="0.0 ${-lower_arm_r - gearbox_l / 2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="gearbox_link"/>
        <child link="lower_arm_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="${-pi}" upper="${pi}" effort="100.0" velocity="100.0"/>
    </joint>

    <joint name="lower_arm_wrist_joint" type="revolute">
        <origin xyz="0.0 0.0 ${lower_arm_l + 0.0927471}" rpy="0.0 0.0 0.0"/>
        <parent link="lower_arm_link"/>
        <child link="wrist_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="${-pi}" upper="${pi}" effort="100.0" velocity="100.0"/>
    </joint>

    <joint name="wrist_wrist_rotation_joint" type="revolute">
        <origin xyz="0.0 0.0 ${wrist_l}" rpy="0.0 0.0 0.0"/>
        <parent link="wrist_link"/>
        <child link="wrist_rotation_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="-${pi}" upper="${pi}" effort="100.0" velocity="100.0"/>
    </joint>

    <joint name="wrist_rotation_left_finger_joint" type="revolute">
        <origin xyz="0.0 ${-finger_l * 2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="wrist_rotation_link"/>
        <child link="left_finger"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100.0" velocity="100.0"/>
    </joint>

     <joint name="wrist_rotation_right_finger_joint" type="revolute">
        <origin xyz="0.0 ${finger_l * 2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="wrist_rotation_link"/>
        <child link="right_finger"/>
        <axis xyz="1.0 0.0 0.0"/>
        <mimic joint="wrist_rotation_left_finger_joint" multiplier="${-1}"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100.0" velocity="100.0"/>
    </joint>

</robot>
